#!/usr/bin/env python3
"""Generate docs/reference/options.md from the modules/ tree.

Best-effort *textual* scan of ``<root>/modules/**/*.nix`` for
``options.<path> = mkOption { ... };`` declarations. It pulls out the
option's dotted path plus, where present, its ``type``, ``default`` and
``description`` fields, and renders a sorted Markdown page.

This is a stopgap. ubuntnix is pre-M1: there is no flake yet, so there is
nothing to `nix eval`. Once modules/flake.nix exist, this textual regex
scan should be replaced by a nix-eval-based extractor that evaluates the
real option declarations (types, defaults, submodules, merged descriptions,
etc.) instead of grepping source text. Anything this script cannot parse
(multi-line attrsets as defaults, computed paths, `lib.mkOption` written
across unusual formatting, etc.) is simply omitted rather than guessed at.

The output is deterministic: for the same input tree it always produces
byte-identical output, sorted by option path then by declaring file.

Usage:
    gen_reference.py [--root PATH] [--out PATH]

--root defaults to $UBX_REPO_ROOT, falling back to the parent of the
       docs/ directory that contains this script.
--out  defaults to docs/reference/options.md next to this script (so
       tests can point it elsewhere with --out).
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path
from typing import Optional

# Matches `options.<dotted.path> = [prefix.]mkOption {`, capturing the
# dotted attribute path and leaving the parser positioned at the opening
# brace of the mkOption argument. `prefix.` covers the common `lib.mkOption`
# spelling; bare `mkOption` (imported via `inherit (lib) mkOption;` or
# `with lib;`) is also matched.
OPTION_HEAD_RE = re.compile(
    r"options\.(?P<path>[A-Za-z0-9_]+(?:\.[A-Za-z0-9_]+)*)"
    r"\s*=\s*(?:[A-Za-z0-9_]+\.)?mkOption\s*(?P<brace>\{)"
)

# Best-effort field extraction inside an mkOption {...} block. Non-greedy up
# to the next `;`, so this only handles single-statement (not nested-attrset)
# field values — sufficient for the common `type = lib.types.str;` /
# `default = "x";` / `description = "...";` forms.
FIELD_RE = re.compile(r"\b(type|default|description)\s*=\s*(.*?);", re.DOTALL)


def extract_block(text: str, open_brace_idx: int) -> str:
    """Return the balanced-brace block starting at open_brace_idx (inclusive)."""
    depth = 0
    i = open_brace_idx
    n = len(text)
    while i < n:
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[open_brace_idx : i + 1]
        i += 1
    # Unterminated block (shouldn't happen in valid Nix) — return what we have.
    return text[open_brace_idx:]


def find_options(text: str) -> list[dict]:
    """Best-effort extraction of mkOption declarations from one file's text."""
    found = []
    for m in OPTION_HEAD_RE.finditer(text):
        path = m.group("path")
        block = extract_block(text, m.start("brace"))
        fields: dict[str, str] = {}
        for fm in FIELD_RE.finditer(block):
            key = fm.group(1)
            if key not in fields:
                fields[key] = " ".join(fm.group(2).split())
        entry = {"path": path, **fields}
        found.append(entry)
    return found


def render_markdown(
    root: Path,
    modules_dir_exists: bool,
    files: list[Path],
    options: list[dict],
) -> str:
    lines: list[str] = []
    lines.append("<!-- Generated by docs/gen_reference.py — do not edit by hand. -->")
    lines.append("")
    lines.append("# Options and modules reference")
    lines.append("")
    lines.append(
        "This page is regenerated in CI from the current state of the tree "
        "(never committed) so it can never drift from the code, per "
        "SPEC.md's G10."
    )
    lines.append("")

    if not modules_dir_exists:
        lines.append(f"Scanned: `modules/` under `{root}` — directory not found.")
        lines.append("")
        lines.append(
            "ubuntnix is pre-M1: no `modules/` tree exists in the repository "
            "yet, so no options are declared."
        )
        lines.append("")
        return "\n".join(lines) + "\n"

    lines.append(
        f"Scanned: `modules/` under `{root}` — {len(files)} `.nix` file(s) found."
    )
    lines.append("")

    if not options:
        lines.append(
            "No option declarations (`mkOption`) were found under `modules/` yet."
        )
        lines.append("")
        return "\n".join(lines) + "\n"

    for opt in options:
        lines.append(f"## `{opt['path']}`")
        lines.append("")
        if "type" in opt:
            lines.append(f"- **type:** `{opt['type']}`")
        if "default" in opt:
            lines.append(f"- **default:** `{opt['default']}`")
        if "description" in opt:
            desc = opt["description"]
            if len(desc) >= 2 and desc.startswith('"') and desc.endswith('"'):
                desc = desc[1:-1]
            lines.append(f"- **description:** {desc}")
        lines.append(f"- **declared in:** `{opt['file']}`")
        lines.append("")

    return "\n".join(lines) + "\n"


def default_root() -> Path:
    env_root = os.environ.get("UBX_REPO_ROOT")
    if env_root:
        return Path(env_root)
    # parent of the docs/ directory that contains this script
    return Path(__file__).resolve().parent.parent


def default_out() -> Path:
    return Path(__file__).resolve().parent / "reference" / "options.md"


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="repo root to scan for modules/ (default: $UBX_REPO_ROOT or "
        "the parent of the docs/ dir containing this script)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="output path for the generated Markdown page "
        "(default: docs/reference/options.md next to this script)",
    )
    args = parser.parse_args(argv)

    root = (args.root if args.root is not None else default_root()).resolve()
    out = (args.out if args.out is not None else default_out()).resolve()

    modules_dir = root / "modules"
    modules_dir_exists = modules_dir.is_dir()

    files: list[Path] = []
    options: list[dict] = []
    if modules_dir_exists:
        files = sorted(modules_dir.rglob("*.nix"))
        for f in files:
            text = f.read_text(errors="replace")
            for opt in find_options(text):
                opt["file"] = str(f.relative_to(root))
                options.append(opt)
        options.sort(key=lambda o: (o["path"], o["file"]))

    content = render_markdown(root, modules_dir_exists, files, options)

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content)

    print(
        f"wrote {out} ({len(options)} option(s) from {len(files)} file(s) "
        f"under {modules_dir})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
