#!/usr/bin/env bash
# tests/unit/070-boot-grub-cfg-gen.sh — bin/ubx-gen-grub-cfg: real functional
# tests against fixture generation lists (SPEC.md §4.2/§4.3; GitHub issue
# #10, milestone M1's "GRUB generation machinery" line item).
#
# Unlike the 030/041/060/061-style "static wiring" tests (which grep source
# text because this harness has no `nix` to actually evaluate anything),
# bin/ubx-gen-grub-cfg is a plain, dependency-free bash script — so this
# test runs it for real, against fixture generation lists, and asserts on
# its actual stdout/exit code. This is the "bash unit test asserting
# against a fixture list of generations" the issue's scope calls for.
set -u

cd "$UBX_REPO_ROOT" || exit 1

fails=0
fail() {
  echo "FAIL: $1" >&2
  fails=$((fails + 1))
}

gen="$UBX_REPO_ROOT/bin/ubx-gen-grub-cfg"
[ -x "$gen" ] || {
  echo "FAIL: $gen does not exist or is not executable" >&2
  exit 1
}

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# -- --help / -h --------------------------------------------------------
for flag in --help -h; do
  out="$("$gen" "$flag" 2>&1)"
  rc=$?
  [ "$rc" -eq 0 ] || fail "'$flag' should exit 0, got $rc"
  for word in --generations --default --timeout --out; do
    case "$out" in
      *"$word"*) ;;
      *) fail "'$flag' output missing '$word'" ;;
    esac
  done
done

# -- unknown option: usage to stderr, exit 2 (mirrors bin/ubx-resolve) ---
out="$("$gen" --this-flag-does-not-exist 2>&1)"
rc=$?
[ "$rc" -eq 2 ] || fail "an unknown option should exit 2, got $rc"
case "$out" in
  *"usage"*) ;;
  *) fail "unknown-option output missing 'usage', got: $out" ;;
esac

# -- --generations is required -------------------------------------------
out="$("$gen" 2>&1)"
rc=$?
[ "$rc" -ne 0 ] || fail "no --generations should fail, got exit 0"
case "$out" in
  *"--generations"*) ;;
  *) fail "missing --generations error should mention it, got: $out" ;;
esac

# -- missing file -----------------------------------------------------------
out="$("$gen" --generations "$work/does-not-exist.tsv" 2>&1)"
rc=$?
[ "$rc" -ne 0 ] || fail "a nonexistent --generations file should fail, got exit 0"

# -- single-generation fixture: exact byte-for-byte expected output ---------
single="$work/single.tsv"
printf '1\tubuntnix generation 1 (linux-image-virtual)\t/vmlinuz-6.8.0-31-generic\t/initrd.img-6.8.0-31-generic\t/dev/vda2\tquiet splash init=/usr/lib/systemd/systemd\n' > "$single"

expected="$work/single.expected"
cat > "$expected" <<'EOF'
# Generated by bin/ubx-gen-grub-cfg -- DO NOT EDIT BY HAND.
# SPEC.md §4.2/§4.3: one menuentry per generation. Regenerate via
# nix/boot.nix's grubCfg (or this script directly) instead.

set default="1"
set timeout="5"

menuentry 'ubuntnix generation 1 (linux-image-virtual)' --id 'ubuntnix-generation-1' {
    insmod part_msdos
    insmod fat
    linux /vmlinuz-6.8.0-31-generic root=/dev/vda2 ro quiet splash init=/usr/lib/systemd/systemd
    initrd /initrd.img-6.8.0-31-generic
}
EOF

actual="$work/single.actual"
"$gen" --generations "$single" > "$actual"
rc=$?
[ "$rc" -eq 0 ] || fail "single-generation render should exit 0, got $rc"
diff -u "$expected" "$actual" > "$work/single.diff" 2>&1 || {
  fail "single-generation render did not match the expected fixture output exactly"
  cat "$work/single.diff" >&2
}

# -- --out FILE writes the same content a stdout capture would ------------
"$gen" --generations "$single" --out "$work/single.viaout"
diff -u "$actual" "$work/single.viaout" > /dev/null 2>&1 ||
  fail "--out FILE did not produce the same content as stdout"

# -- multi-generation fixture: order preserved, comments/blank lines
#    skipped, default defaults to the FIRST listed generation -------------
multi="$work/multi.tsv"
cat > "$multi" <<'EOF'
# a leading comment, and a blank line below

3	Generation 3 (newest)	/vmlinuz-3	/initrd.img-3	/dev/vda4	quiet splash
1	Generation 1 (oldest)	/vmlinuz-1	/initrd.img-1	/dev/vda2	quiet
2	Generation 2	/vmlinuz-2	/initrd.img-2	/dev/vda3	quiet splash debug
EOF

multi_out="$work/multi.out"
"$gen" --generations "$multi" > "$multi_out"

grep -q 'set default="3"' "$multi_out" ||
  fail "multi-generation render should default to the FIRST listed generation's index (3), not sort numerically"

# Menu entries must appear in the FILE's own order (3, then 1, then 2) --
# this script must never silently reorder generations (see its own header).
order="$(grep -oE "ubuntnix-generation-[0-9]+" "$multi_out" | sed 's/ubuntnix-generation-//')"
expected_order="3
1
2"
[ "$order" = "$expected_order" ] ||
  fail "menu entries were not emitted in the generation list's own line order (got: $(echo "$order" | tr '\n' ' '))"

# -- --default overrides which generation index GRUB defaults to ----------
multi_default="$work/multi-default.out"
"$gen" --generations "$multi" --default 2 --timeout 15 > "$multi_default"
grep -q 'set default="2"' "$multi_default" ||
  fail "--default 2 should set GRUB's default to generation index 2"
grep -q 'set timeout="15"' "$multi_default" ||
  fail "--timeout 15 should set GRUB's menu timeout to 15"

# -- --default pointing at a nonexistent generation index must fail -------
out="$("$gen" --generations "$multi" --default 99 2>&1)"
rc=$?
[ "$rc" -ne 0 ] || fail "--default 99 (no such generation) should fail, got exit 0"
case "$out" in
  *"99"*) ;;
  *) fail "--default 99 error should mention the bad index, got: $out" ;;
esac

# -- a title containing a single quote is safely escaped in GRUB syntax ---
quoted="$work/quoted.tsv"
printf "1\tit's a test\t/vmlinuz\t/initrd.img\t/dev/vda2\t\n" > "$quoted"
quoted_out="$("$gen" --generations "$quoted")"
case "$quoted_out" in
  *"menuentry 'it'\\''s a test'"*) ;;
  *)
    fail "a single quote in a generation title was not escaped using GRUB's '\\'' idiom"
    echo "$quoted_out" >&2
    ;;
esac

# -- malformed records fail loudly, with the offending line number --------
bad_index="$work/bad-index.tsv"
printf 'not-a-number\tTitle\t/vmlinuz\t/initrd.img\t/dev/vda2\t\n' > "$bad_index"
out="$("$gen" --generations "$bad_index" 2>&1)"
rc=$?
[ "$rc" -ne 0 ] || fail "a non-integer generation index should fail, got exit 0"
case "$out" in
  *":1:"*) ;;
  *) fail "malformed-index error should cite the line number (1), got: $out" ;;
esac

relative_kernel="$work/relative-kernel.tsv"
printf '1\tTitle\tvmlinuz-not-absolute\t/initrd.img\t/dev/vda2\t\n' > "$relative_kernel"
out="$("$gen" --generations "$relative_kernel" 2>&1)"
rc=$?
[ "$rc" -ne 0 ] || fail "a relative kernelPath should fail, got exit 0"
case "$out" in
  *"kernelPath"*) ;;
  *) fail "relative-kernelPath error should mention 'kernelPath', got: $out" ;;
esac

empty_root="$work/empty-root.tsv"
printf '1\tTitle\t/vmlinuz\t/initrd.img\t\t\n' > "$empty_root"
out="$("$gen" --generations "$empty_root" 2>&1)"
rc=$?
[ "$rc" -ne 0 ] || fail "an empty rootDevice should fail, got exit 0"

duplicate="$work/duplicate.tsv"
printf '1\tA\t/vmlinuz-a\t/initrd.img-a\t/dev/vda2\t\n1\tB\t/vmlinuz-b\t/initrd.img-b\t/dev/vda3\t\n' > "$duplicate"
out="$("$gen" --generations "$duplicate" 2>&1)"
rc=$?
[ "$rc" -ne 0 ] || fail "a duplicate generation index should fail, got exit 0"
case "$out" in
  *"duplicate"*) ;;
  *) fail "duplicate-index error should mention 'duplicate', got: $out" ;;
esac

empty_file="$work/empty.tsv"
: > "$empty_file"
out="$("$gen" --generations "$empty_file" 2>&1)"
rc=$?
[ "$rc" -ne 0 ] || fail "an empty generations file should fail, got exit 0"

# comment-only / blank-only file behaves the same as truly empty -----------
comment_only="$work/comment-only.tsv"
printf '# just a comment\n\n   \n' > "$comment_only"
out="$("$gen" --generations "$comment_only" 2>&1)"
rc=$?
[ "$rc" -ne 0 ] || fail "a comment/blank-only generations file should fail, got exit 0"

exit "$fails"
